### ISSUE TITLE
Any way to prevent survival players from seeing their death coordinates? Unfortunately this mod (1.12.2) makes dying in survival a trivial experience.

### ISSUE THREAD

**Issue by roccscout** [henkelmax/corpse#18] opened 2020-10-30 20:58 UTC
I'm just looking for a simple corpse mod, without seeing your coordinates or being able to teleport in survival?

**Comment by henkelmax** [comment] 2020-10-30 22:25
Duplicate of #17

**Closed by henkelmax** 2020-10-30 22:25 UTC
Labels: enhancement
