### ISSUE TITLE
non-OP users on server can't access their corpse on 1.16.3 servers

### ISSUE THREAD

**Issue by BedrockLegends** [henkelmax/corpse#19] opened 2020-11-01 20:39 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
As soon as a normal player dies on our 1.16.3 server, they cant access their Corpse and only Ops can
**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

I dont have a log file, its similar to this https://github.com/henkelmax/corpse/issues/12

**Versions**
- Minecraft version 1.16.3
- Forge version 34.1.35
- Mod version 1.16.3-1.1.8

**Comment by BedrockLegends** [comment] 2020-11-01 20:42
Both the client and Server have the same verison

**Comment by henkelmax** [comment] 2020-11-02 08:58
Duplicate of #12

**Closed by henkelmax** 2020-11-02 08:58 UTC
Labels: bug
