### ISSUE TITLE
Compatibility Crash with EpicFight Mod

### ISSUE THREAD

**Issue by Malloks** [henkelmax/corpse#59] opened 2021-09-04 12:49 UTC
**Please read the [FAQ](https://modrepo.de/minecraft/corpse/faq) before submitting a bug report!**

**Bug description**
Crashes immediately upon death when both Corpse Mod and EpicFight Mod are on, my guess is that Copse Mod tries to use the player model of the EpicFight Mod which is custom and crashes (after the crash the world is rolled back before the death)

**Steps to reproduce the issue**
1. Go to 'Minecraft'
2. Click on ''chat'
3. Scroll down to 'type /kill (or die in any other way)'
4. See an error - Crash

**Expected behaviour**
Get the respawn screen, respawn and find my corpse

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).
- No logs, the crash freezes the game for infinity and the only way to close it is via task manager which nullifies any log feedback

**Versions**
- Minecraft version - 1.16.5
- Forge version - 36.2.2
- Mod version - 1.0.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
-Epic Fight Mod

**Screenshots (Optional)**
No screenshots, just an immediate crash

**Comment by henkelmax** [comment] 2021-09-04 14:58
Duplicate of #52

**Closed by henkelmax** 2021-09-04 14:58 UTC
Labels: bug
