### ISSUE TITLE
1.16 - corpse won't appear in nether

### ISSUE THREAD

**Issue by connynordlund** [henkelmax/corpse#14] opened 2020-10-27 19:22 UTC
If you die in the Nether, the corpse won't appear but the tag will be in the world.
Forge version: 1.16.3-forge-34-1-25

**Comment by henkelmax** [comment] 2020-10-27 19:25
Please use the provided issue template.

**Comment by henkelmax** [comment] 2020-10-27 19:26
This is also a duplicate of #11

**Closed by henkelmax** 2020-10-27 19:25 UTC
Labels: invalid
