### ISSUE TITLE
Can't loot bodies as OP or Non-OP or in Creative.

### ISSUE THREAD

**Issue by ColbyHF** [henkelmax/corpse#13] opened 2020-10-24 22:45 UTC
**Bug description**
Non-op and Op along with creative won't let me grab items off the corpse. Before I was able to loot my body I died 3 times, after that, I lost the ability to loot my body.

**Steps to reproduce the issue**
1. Die
2. Right-Click on body
3. Click Items
4. Then nothing happens

**Expected behavior**
Right-click body and should be lootable.

**Log files**
`[24Oct2020 22:15:19.218] [Netty Epoll Server IO #43/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.ModIdArgument@6a315763 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[24Oct2020 22:15:19.218] [Netty Epoll Server IO #43/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize net.minecraftforge.server.command.EnumArgument@5560ebf2 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!`

https://gist.github.com/ColbyHF/d1056ad1033aa9f4945c2033ad387da6

**Versions**
- Minecraft version 1.16.3
- Forge version 34.1.25
- Mod version 1.16.3-1.1.8

**Other mods**
Modpack All the mods 6

**Comment by ColbyHF** [comment] 2020-10-24 23:56
Found a fix. Mod versions were differing with the server and client. Switched to make them match up and I was able to obtain my loot from dead bodies.

**Comment by henkelmax** [comment] 2020-10-25 08:54
Duplicate of #12

**Closed by henkelmax** 2020-10-25 08:54 UTC
Labels: bug
