### ISSUE TITLE
PlayerRevive&Corpse

### ISSUE THREAD

**Issue by qellyka** [henkelmax/corpse#179] opened 2024-02-16 15:58 UTC
### Bug description

Hello, I wanted to ask if they would help.  In short, I installed the PlayerRevive and Corpse mod on the server and on the client, but I ran into a problem. The PlayerRevive mod works on the server, but after the death of the player's corpse does not remain, although the Corpse mod is worth it, and if I go into a single world and open a network game and die, then the corpse will remain.

### Minecraft version

1.18.2

### Mod version

1.18.2-1.0.1

### Mod loader and version

Forge 40.2.,0

### Steps to reproduce

1.Add corpse and PlayerRevive mods to the server
2. To die
3. There is no corpse

### Expected behavior

The appearance of a corpse after the final death

### Log files

https://gist.github.com/qellyka/d7ee795dc002e7f9a6a2e6aecd36f363

**Comment by henkelmax** [comment] 2024-02-16 16:09
Duplicate of #177

**Closed by henkelmax** 2024-02-16 16:09 UTC
Labels: triage
