### ISSUE TITLE
Items dropping on death instead of staying in corpse inventory

### ISSUE THREAD

**Issue by GoliathX211** [henkelmax/corpse#46] opened 2021-05-15 20:18 UTC
**Bug description**
Upon death on the multiplayer server I am playing on, items are dropped on the ground rather than being placed in the corpse inventory. This bug does not occur with the modpack I am playing with on a singleplayer world.

**Expected behavior**
I expected items to be in the corpse inventory upon death, yet the items were entities in the world.

**Log files**
I cannot provide log files due to not being the server owner.

**Versions**
- Minecraft version: 1.16.5
- Forge version: 36.1.4
- Mod version: "corpse-1.16.5-1.0.1.jar"

**Other mods**
The modpack is Better Minecraft [Forge] v16.5
(I noticed that the other mods is not an issue by appearances due to testing in a singleplayer world working flawlessly)

**Suspected problem**
I think that the issue is caused by the engine "Mohist" being used for the server. If you are unaware, it allows use of forge mods and server plugins.

Contact me on discord at GoliathX211#4373 if you need to discuss further information.

**Comment by henkelmax** [comment] 2021-05-15 21:20
Duplicate of #43

**Closed by henkelmax** 2021-05-15 21:20 UTC
Labels: bug

**Comment by DisplayPort** [comment] 2021-05-29 23:33
I had the same problem and it turns out it was being caused by the Mohist API, they fixed it in build 604 or 605. Using the currently latest 614 build seems to work perfectly fine with Corpse and GraveStone now. Thought id share this to help the few others having this problem.
