### ISSUE TITLE
GameCrash - SkullModelBase

### ISSUE THREAD

**Issue by TheCherry** [henkelmax/corpse#90] opened 2022-04-24 16:18 UTC
**Bug description**
Game crash imminently if a player comes in the near of the corpse and is unable to join the server again.
I had to teleport the players fast after join. Still I can't join, because I am dead and I am unable to teleport me out of this situation.
The Server have no errors.

**Steps to reproduce the issue**
I died in the nether with a friend near. I had a piglit skull as a head armour. As I died, our both games crashed. 
We tried to remove optifine, still its don't work.

**Log files**
https://crashy.net/3jpVHxq1GhR1BdZGs1Sm

**Versions**
- 1.18.1
- 39.1.0
- Corpse 1.18.1-1.0.4

**Other mods**
<details>
<summary>SPOILER</summary>

```
Corpse 1.18.1-1.0.4 - may have caused crash (corpse)
AI-Improvements 0.4.0 (aiimprovements)
Alex's Mobs 1.17.4 (alexsmobs)
Alex's Mobs Mod Music 0.0NONE (peepomod)
Ambient Additions 1.18.1-0.6.2 (ambientadditions)
Ambient Sounds 3.0.3 (ambientsounds)
Amplified Nether + Seed Fix 0.0NONE (seedfix)
AppleSkin 2.4.0+mc1.18 (appleskin)
AutoRegLib 1.7-53 (autoreglib)
Balm 2.4.3+0 (balm)
Basic End Ores 2.0.0 (beo)
Basic Nether Ores 7.1.2 (bno)
Blue Skies 1.3.4 (blue_skies)
Castle in the sky 1.18.1 (castle_in_the_sky)
Cataclysm Mod 1.0 (cataclysm)
CC: Tweaked 1.100.2 (computercraft)
Champions 1.18.2-2.1.5.1 (champions)
Chunky 1.2.164 (chunky)
Citadel 1.10.10 (citadel)
Clumps 8.0.0+5 (clumps)
Configured 1.5.3 (configured)
Controlling 9.0+15 (controlling)
CookingForBlockheads 11.1.0 (cookingforblockheads)
Copper's Delight 1.2 (coppersdelight)
Corn Delight 1.0.8-1.18.1 (corn_delight)
Cosmetic Netherite 1.0.4 (cosmetic_netherite)
CosmeticArmorReworked 1.18.1-v1a (cosmeticarmorreworked)
CraftTweaker 9.0.81 (crafttweaker)
Create 0.4f (create)
Create Crafts & Additions 1.18.1-20220420a (createaddition)
Create Deco 1.2.5-1.18 (createdeco)
Create: Alloyed 1.18.1 (alloyed)
Create: Steam Powered 1.18.1-2.0.1-alpha (steampowered)
CreativeCore 2.5.0 (creativecore)
Creeper Overhaul 0.3.0 (creeperoverhaul)
Curios API 1.18.1-5.0.6.2 (curios)
Dungeon Crawl 2.3.7 (dungeoncrawl)
EnchantmentDescriptions 9.0.13 (enchdesc)
End Remastered 5.0-R-1.18.1 (endrem)
Enderite 1.3.4-1.18.1 (lolenderite)
Enderite's Delight 1.2 (enderitesdelight)
Epic Knights: Armor and Weapon 1.0 (magistuarmory)
Equipment Compare 1.2.12 (equipmentcompare)
Farmer's Delight 1.18.1-1.0.4 (farmersdelight)
Farming for Blockheads 9.0.3 (farmingforblockheads)
Flywheel 1.18-0.6.1.63 (flywheel)
Forge 39.1.0 (forge)
ForgeEndertech 08.0.1.0 (forgeendertech)
GeckoLib 3.0.11 (geckolib3)
Goblins & Dungeons 1.0.7 (goblinsanddungeons)
HT's TreeChop 0.15.7 (treechop)
Iceberg 1.0.40 (iceberg)
InsaneLib 1.4.3 (insanelib)
JEI Enchantment Info 1.17.1-2.0.0 (jeienchantmentinfo)
JEI Tweaker 3.0.0.5 (jeitweaker)
Journeymap 5.8.1 (journeymap)
Just Enough Items 9.4.1.172 (jei)
Lootr 0.1.15.50 (lootr)
Macaw's Bridges 2.0.2 (mcwbridges)
Macaw's Bridges - Oh The Biome 1.18.1-1.0 (macawsbridgesbyg)
Macaw's Doors 1.0.6 (mcwdoors)
Macaw's Fences and Walls 1.0.4 (mcwfences)
Macaw's Furniture 3.0.0 (mcwfurnitures)
Macaw's Lights and Lamps 1.0.3 (mcwlights)
Macaw's Paintings 1.0.3 (mcwpaintings)
Macaw's Roofs 2.1.2 (mcwroofs)
Macaw's Roofs - Oh The Biomes 1.18.1-1.1 (macawsroofsbyg)
Macaw's Trapdoors 1.0.5 (mcwtrpdoors)
Macaw's Windows 2.0.3 (mcwwindows)
Mantle 1.8.37 (mantle)
Minecraft 1.18.1 (minecraft)
Mouse Tweaks 2.21 (mousetweaks)
Mysterious Mountain Lib 1.0.0-1.18.1 (mmlib)
Not Enough Crashes 4.1.4+1.18.1 (notenoughcrashes)
Oh The Biomes You'll Go 1.3.5.13 (byg)
Pollution of the Realms 05.0.2.0 (adpother)
Progressive Bosses 3.5.4 (progressivebosses)
Quark 3.1-340 (quark)
Refined Storage 1.10.1 (refinedstorage)
Seed Fix + Terralith 0.0NONE (seedfix_forge)
Selene 1.18-1.13.2 (selene)
Sky Villages 1.0.0 (skyvillages)
Sophisticated Backpacks 1.18.1-3.15.15.550 (sophisticatedbackpacks)
Steel's Delight 1.1 (steelsdelight)
Storage Drawers 10.1.1 (storagedrawers)
Structure Gel API 2.1.3 (structure_gel)
Survive 1.18.1-6.1.12 (survive)
TerraBlender 1.18.1-1.1.0.77 (terrablender)
The One Probe 1.18-5.0.4 (theoneprobe)
Tinkers' Construct 3.4.2.60 (tconstruct)
UnionLib 6.2.0 (unionlib)
Valhelsia Core 1.18.1-0.3.2 (valhelsia_core)
Valhelsia Structures 1.18.1-0.1.1 (valhelsia_structures)
Waystones 9.0.4 (waystones)
When Dungeons Arise 2.1.49d-1.18.1 (dungeons_arise)
YUNG's API 1.18.1-Forge-26 (yungsapi)
YUNG's Better Dungeons 1.18.1-1.0.1 (betterdungeons)
```
</details>

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment] 2022-04-24 16:20
Duplicate of #85

**Closed by henkelmax** 2022-04-24 16:20 UTC
Labels: bug

**Comment by TheCherry** [comment] 2022-04-24 16:27
Oh ok and is there a fix for it now? At last a temporary fix? We can't enter now the nether and I don't even can join our game.

**Comment by henkelmax** [comment] 2022-04-24 16:29
Yes, just update the mod!
